//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DEVICE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DEVICE()
        {
            this.WEATHER_DATA = new HashSet<WEATHER_DATA>();
        }
    
        public int ID { get; set; }
        public int LOCATION_ID { get; set; }
        public int TYPE { get; set; }
    
        public virtual LOCATION LOCATION { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WEATHER_DATA> WEATHER_DATA { get; set; }
    }
}
