//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WeatherAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class WEATHER_DATA
    {
        public int ID { get; set; }
        public byte[] TIME_STAMP { get; set; }
        public int DEIVCE_ID { get; set; }
        public string DATA { get; set; }
    
        public virtual DEVICE DEVICE { get; set; }
    }
}
